CREATE DATABASE Atividade_bd9;

USE Atividade_bd9;

CREATE TABLE grupo(
	letra_identificadora char(1) PRIMARY KEY,
    lugar1 varchar(30) DEFAULT 'A definir',
    lugar2 varchar(30) DEFAULT 'A definir',
    lugar3 varchar(30) DEFAULT 'A definir',
    lugar4 varchar(30) DEFAULT 'A definir');
    
CREATE TABLE pais_sede(
	nome_pais varchar(30) PRIMARY KEY,
    numero_jogos_do_pais INT CHECK (numero_jogos_do_pais >= 0),
    numero_estadios INT,
    nome_mascote varchar(30));
    
CREATE TABLE estadio(
	id INT PRIMARY KEY,
    cidade varchar(50),
    capacidade_maxima INT CHECK (capacidade_maxima > 0),
    nome varchar(30),
    fk_pais_sede_nome_pais varchar(30),
    FOREIGN KEY (fk_pais_sede_nome_pais) REFERENCES pais_sede(nome_pais) 
    ON DELETE CASCADE);
    
CREATE TABLE selecao(
	inscricao INT PRIMARY KEY,
	ranking_da_fifa INT UNIQUE,
    media_idade INT, 
    media_gols INT DEFAULT 0,
    continente varchar(30),
    fk_grupo_letra_identificadora char(1),
    pontuacao INT CHECK (pontuacao >= 0),
    nome varchar(30) NOT NULL,
	FOREIGN KEY(fk_grupo_letra_identificadora) REFERENCES grupo(letra_identificadora) ON DELETE CASCADE);

CREATE TABLE mascote(
	id INT PRIMARY KEY,
    nome varchar(30),  
    fk_selecao_inscricao INT,
	FOREIGN KEY (fk_selecao_inscricao) REFERENCES selecao(inscricao) ON DELETE CASCADE);

CREATE TABLE comissao_tecnica(
    nome varchar(30),
    nacionalidade varchar(30),
	inscricao INT PRIMARY KEY, 
    fk_inscricao_selecao INT,
    FOREIGN KEY (fk_inscricao_selecao) REFERENCES selecao(inscricao) ON DELETE CASCADE);
    
CREATE TABLE treinador(
	fk_comissao_tecnica_inscricao INT PRIMARY KEY,
	estilo_de_jogo varchar(30),
    esquema_tatico_pref varchar(30),
	FOREIGN KEY(fk_comissao_tecnica_inscricao) REFERENCES comissao_tecnica(inscricao) ON DELETE CASCADE);

CREATE TABLE preparador_fisico(
	fk_comissao_tecnica_inscricao INT PRIMARY KEY,
	especializacao varchar(30),
    metodologia_treino varchar(50),
	FOREIGN KEY (fk_comissao_tecnica_inscricao) REFERENCES comissao_tecnica(inscricao) ON DELETE CASCADE);
    
CREATE TABLE auxiliar_tecnico(
	fk_comissao_tecnica_inscricao INT PRIMARY KEY,
	especialidade varchar(30),
    foco_setorial varchar(30),
	FOREIGN KEY (fk_comissao_tecnica_inscricao) REFERENCES comissao_tecnica(inscricao) ON DELETE CASCADE);
    
CREATE TABLE jogo(
	id INT PRIMARY KEY,
    placar varchar(60),
    data DATETIME, 
    vencedor varchar(30), 
	perdedor varchar(30), 
	tipo_jogo varchar(30));
    
CREATE TABLE contido(
	fk_jogo_id INT, 
	fk_selecao_inscricao INT,
    CONSTRAINT pk_contido PRIMARY KEY(fk_jogo_id, fk_selecao_inscricao),
	FOREIGN KEY (fk_selecao_inscricao) REFERENCES selecao(inscricao) ON DELETE CASCADE,
	FOREIGN KEY (fk_jogo_id) REFERENCES jogo(id) ON DELETE CASCADE);

CREATE TABLE jogador(
	inscricao INT PRIMARY KEY, 
    numero_da_camisa INT, 
    posicao varchar(30), 
    nome varchar(30) NOT NULL, 
    idade INT, 
    fk_selecao_inscricao INT, 
    capitao INT,
    FOREIGN KEY (fk_selecao_inscricao) REFERENCES selecao(inscricao) ON DELETE SET NULL,
    FOREIGN KEY (capitao) REFERENCES jogador(inscricao) ON DELETE CASCADE);
    
CREATE TABLE posicao (
    NomePosicao VARCHAR(30),
    inscricao_jogador INT,
    PRIMARY KEY (NomePosicao, inscricao_jogador),
    FOREIGN KEY (inscricao_jogador) 
        REFERENCES jogador(inscricao) 
        ON DELETE CASCADE
);
    
CREATE TABLE participa_jogo_estadio_jogador(
	fk_jogador_inscricao INT,
	fk_jogo_id INT, 
	fk_estadio_id INT,
	CONSTRAINT pk_participa PRIMARY KEY(fk_jogador_inscricao, fk_jogo_id),
 	FOREIGN KEY (fk_jogador_inscricao) REFERENCES jogador(inscricao) ON DELETE CASCADE,
    FOREIGN KEY (fk_jogo_id) REFERENCES jogo(id) ON DELETE CASCADE,
	FOREIGN KEY (fk_estadio_id) REFERENCES estadio(id) ON DELETE CASCADE);

INSERT INTO grupo (letra_identificadora, lugar1, lugar2, lugar3, lugar4) VALUES
('A', 'Brasil', 'Alemanha', 'Japao', 'Tunisia'),
('B', 'Argentina', 'Franca', 'Coreia do Sul', 'Gana'),
('C', 'Belgica', 'Espanha', 'Marrocos', 'Canada'),
('D', 'Inglaterra', 'Uruguai', 'Ira', 'Camaroes'),
('E', 'Portugal', 'Holanda', 'Saudi Arabia', 'Senegal'),
('F', 'Italia', 'Croacia', 'Australia', 'Equador'),
('G', 'Estados Unidos', 'Dinamarca', 'Costa Rica', 'Mali'),
('H', 'Mexico', 'Suica', 'Panama', 'Argelia'),
('I', 'Colombia', 'Suecia', 'Honduras', 'Egito'),
('J', 'Chile', 'Polonia', 'Jamaica', 'Nigeria'),
('K', 'Peru', 'Ucrnia', 'Nova Zelandia', 'Africa do Sul'),
('L', 'Uruguai', 'Austria', 'Iraque', 'Zambia'),
('M', 'Paraguai', 'Turquia', 'Catar', 'Costa do Marfim'),
('N', 'Venezuela', 'Grecia', 'Emirados Arabes', 'Ginea'),
('O', 'Equador', 'Republica Checa', 'Oman', 'Congo'),
('P', 'Bolivia', 'Romenia', 'China', 'Gabao'),
('Q', 'Nicaragua', 'Escocia', 'Siria', 'Togo'),
('R', 'Haiti', 'Irlanda', 'Jordania', 'Benin'),
('S', 'Cuba', 'Gales', 'Kuwait', 'Uganda'),
('T', 'Panama', 'Noruega', 'Bahrein', 'Quenia'),
('U', 'Honduras', 'Finlandia', 'Libano', 'Angola'),
('V', 'El Salvador', 'Islandia', 'Vietna', 'Sudao'),
('W', 'Guatemala', 'Bulgaria', 'Tailandia', 'Ruanda'),
('X', 'Costa Rica', 'Hungria', 'India', 'Burkina Faso'),
('Y', 'Nova Zelandia', 'Servia', 'Malasia', 'Mocambique'),
('Z', 'Australia', 'Eslovaquia', 'Indonesia', 'Madagascar'),
('1', 'Canada', 'Slovenia', 'Filipinas', 'Libia'),
('2', 'Estados Unidos', 'Albania', 'Cingapura', 'Mauricio'),
('3', 'Mexico', 'Montenegro', 'Mianmar', 'Cabo Verde'),
('4', 'Jamaica', 'Macedonia', 'Cazaquistao', 'Mali');

INSERT INTO pais_sede (nome_pais, numero_jogos_do_pais, numero_estadios, nome_mascote) VALUES
('Brasil', 7, 12, 'Fuleco'),
('Alemanha', 6, 10, 'Goleo VI'),
('Franca', 5, 9, 'Footix'),
('Argentina', 4, 8, 'Gauchito'),
('Espanha', 5, 8, 'Naranjito'),
('Italia', 4, 10, 'Ciao'),
('Inglaterra', 4, 7, 'Willie'),
('Mexico', 5, 6, 'Pique'),
('Uruguai', 3, 3, 'Torito'),
('Chile', 3, 4, 'Al表o'),
('Estados Unidos', 6, 11, 'Striker'),
('Japao', 5, 7, 'Ato'),
('Coreia do Sul', 5, 7, 'Nik'),
('Africa do Sul', 4, 10, 'Zakumi'),
('Catar', 4, 8, 'La''eeb'),
('Portugal', 3, 5, 'Quinas'),
('Holanda', 3, 4, 'Leo'),
('Belgica', 2, 4, 'Diabo'),
('Colombia', 2, 5, 'Cafeterito'),
('Peru', 2, 3, 'Incaico'),
('Ucrnia', 2, 4, 'Slavik'),
('Polonia', 2, 4, 'Siemko'),
('Suica', 3, 4, 'Swissi'),
('Suecia', 3, 5, 'Viking'),
('Russia', 5, 12, 'Zabivaka'),
('Australia', 4, 6, 'Kanga'),
('Canada', 3, 4, 'Moose'),
('Marrocos', 3, 6, 'Lion'),
('Saudi Arabia', 3, 5, 'Desert'),
('Egito', 2, 4, 'Pharaoh');

INSERT INTO estadio (id, cidade, capacidade_maxima, nome, fk_pais_sede_nome_pais) VALUES
(1, 'Rio de Janeiro', 78000, 'Maracana', 'Brasil'),
(2, 'Sao Paulo', 49000, 'Neo Quimica Arena', 'Brasil'),
(3, 'Munique', 75000, 'Allianz Arena', 'Alemanha'),
(4, 'Berlim', 74000, 'Olympiastadion', 'Alemanha'),
(5, 'Paris', 80000, 'Stade de France', 'Franca'),
(6, 'Buenos Aires', 84000, 'Monumental de Nunez', 'Argentina'),
(7, 'Madrid', 81000, 'Santiago Bernabeu', 'Espanha'),
(8, 'Barcelona', 99000, 'Camp Nou', 'Espanha'),
(9, 'Roma', 72000, 'Stadio Olimpico', 'Italia'),
(10, 'Milao', 80000, 'San Siro', 'Italia'),
(11, 'Londres', 90000, 'Wembley', 'Inglaterra'),
(12, 'Cidade do Mexico', 87000, 'Estadio Azteca', 'Mexico'),
(13, 'Montevideo', 60000, 'Centenario', 'Uruguai'),
(14, 'Santiago', 48000, 'Nacional de Chile', 'Chile'),
(15, 'Los Angeles', 90000, 'Rose Bowl', 'Estados Unidos'),
(16, 'Yokohama', 72000, 'Nissan Stadium', 'Japao'),
(17, 'Seul', 66000, 'Seoul World Cup', 'Coreia do Sul'),
(18, 'Joanesburgo', 94000, 'FNB Stadium', 'Africa do Sul'),
(19, 'Doha', 88000, 'Lusail Stadium', 'Catar'),
(20, 'Lisboa', 65000, 'Estadio da Luz', 'Portugal'),
(21, 'Amsterda', 55000, 'Johan Cruyff ArenA', 'Holanda'),
(22, 'Bruxelas', 50000, 'King Baudouin', 'Belgica'),
(23, 'Bogota', 36000, 'El Campin', 'Colombia'),
(24, 'Lima', 43000, 'Estadio Nacional', 'Peru'),
(25, 'Kyiv', 70000, 'Olimpiyskiy', 'Ucrnia'),
(26, 'Varsovia', 58000, 'PGE Narodowy', 'Polonia'),
(27, 'Zurique', 26000, 'Letzigrund', 'Suica'),
(28, 'Estocolmo', 50000, 'Friends Arena', 'Suecia'),
(29, 'Moscou', 81000, 'Luzhniki', 'Brasil'),
(30, 'Sydney', 83000, 'Accor Stadium', 'Australia');

INSERT INTO selecao (inscricao, ranking_da_fifa, media_idade, media_gols, continente, fk_grupo_letra_identificadora, pontuacao, nome) VALUES
(1, 1, 26, 3, 'America do Sul', 'A', 9, 'Brasil'),
(2, 2, 27, 2, 'Europa', 'A', 6, 'Alemanha'),
(3, 3, 25, 4, 'Europa', 'B', 7, 'Franca'),
(4, 4, 28, 2, 'America do Sul', 'B', 4, 'Argentina'),
(5, 5, 26, 1, 'Europa', 'C', 5, 'Belgica'),
(6, 6, 25, 3, 'Europa', 'C', 9, 'Espanha'),
(7, 7, 27, 2, 'Europa', 'D', 6, 'Inglaterra'),
(8, 8, 29, 1, 'America do Sul', 'D', 3, 'Uruguai'),
(9, 9, 28, 2, 'Europa', 'E', 7, 'Portugal'),
(10, 10, 26, 3, 'Europa', 'E', 6, 'Holanda'),
(11, 11, 27, 1, 'Europa', 'F', 4, 'Italia'),
(12, 12, 28, 2, 'Europa', 'F', 5, 'Croacia'),
(13, 13, 25, 2, 'America do Norte', 'G', 6, 'Estados Unidos'),
(14, 14, 24, 1, 'Asia', 'A', 1, 'Japao'),
(15, 15, 26, 1, 'Asia', 'B', 3, 'Coreia do Sul'),
(16, 16, 27, 2, 'Africa', 'C', 4, 'Marrocos'),
(17, 17, 28, 1, 'Africa', 'D', 3, 'Camaroes'),
(18, 18, 26, 2, 'Africa', 'E', 4, 'Senegal'),
(19, 19, 27, 1, 'America do Norte', 'H', 4, 'Mexico'),
(20, 20, 26, 2, 'Europa', 'H', 6, 'Suica'),
(21, 21, 27, 1, 'America do Sul', 'I', 3, 'Colombia'),
(22, 22, 28, 1, 'Europa', 'I', 4, 'Suecia'),
(23, 23, 26, 0, 'Asia', 'E', 1, 'Saudi Arabia'),
(24, 24, 29, 1, 'Africa', 'I', 2, 'Egito'),
(25, 25, 27, 1, 'Oceania', 'F', 1, 'Australia'),
(26, 26, 26, 2, 'America do Norte', 'G', 2, 'Canada'),
(27, 27, 28, 1, 'America do Sul', 'J', 3, 'Chile'),
(28, 28, 27, 1, 'Europa', 'J', 4, 'Polonia'),
(29, 29, 26, 1, 'America do Sul', 'K', 2, 'Peru'),
(30, 30, 28, 1, 'Europa', 'K', 3, 'Ucrnia');

INSERT INTO mascote (id, nome, fk_selecao_inscricao) VALUES
(1, 'Canarinho', 1),
(2, 'Eagle', 2),
(3, 'Rooster', 3),
(4, 'Leonel', 4),
(5, 'Red Devil', 5),
(6, 'Toro', 6),
(7, 'Lionheart', 7),
(8, 'Sol', 8),
(9, 'Navegador', 9),
(10, 'Tulipa', 10),
(11, 'Lupo', 11),
(12, 'Vatreni', 12),
(13, 'Sam', 13),
(14, 'Tanuki', 14),
(15, 'Tiger', 15),
(16, 'Atlas', 16),
(17, 'Indomavel', 17),
(18, 'Lion of Teranga', 18),
(19, 'Chilli', 19),
(20, 'Cow', 20),
(21, 'Coffee', 21),
(22, 'Elk', 22),
(23, 'Falcon', 23),
(24, 'Anubis', 24),
(25, 'Kangaroo', 25),
(26, 'Maple', 26),
(27, 'Condor', 27),
(28, 'Eagle-White', 28),
(29, 'Alpaca', 29),
(30, 'Cossack', 30);

INSERT INTO comissao_tecnica (nome, nacionalidade, inscricao, fk_inscricao_selecao) VALUES
('Comissao Br', 'Brasileira', 1, 1),
('Comissao Ger', 'Alema', 2, 2),
('Comissao Fra', 'Francesa', 3, 3),
('Comissao Arg', 'Argentina', 4, 4),
('Comissao Bel', 'Belga', 5, 5),
('Comissao Esp', 'Espanhola', 6, 6),
('Comissao Eng', 'Inglesa', 7, 7),
('Comissao Uru', 'Uruguaia', 8, 8),
('Comissao Por', 'Portuguesa', 9, 9),
('Comissao Ned', 'Holandesa', 10, 10),
('Comissao Ita', 'Italiana', 11, 11),
('Comissao Cro', 'Croata', 12, 12),
('Comissao Usa', 'Americana', 13, 13),
('Comissao Jap', 'Japonesa', 14, 14),
('Comissao Kor', 'Coreana', 15, 15),
('Comissao Mar', 'Marroquina', 16, 16),
('Comissao Cmr', 'Camaronesa', 17, 17),
('Comissao Sen', 'Senegalesa', 18, 18),
('Comissao Mex', 'Mexicana', 19, 19),
('Comissao Sui', 'Suica', 20, 20),
('Comissao Col', 'Colombiana', 21, 21),
('Comissao Swe', 'Sueca', 22, 22),
('Comissao Ksa', 'Saudita', 23, 23),
('Comissao Egy', 'Egipcia', 24, 24),
('Comissao Aus', 'Australiana', 25, 25),
('Comissao Can', 'Canadense', 26, 26),
('Comissao Chi', 'Chilena', 27, 27),
('Comissao Pol', 'Polonesa', 28, 28),
('Comissao Per', 'Peruana', 29, 29),
('Comissao Ukr', 'Ucraniana', 30, 30);

INSERT INTO treinador (fk_comissao_tecnica_inscricao, estilo_de_jogo, esquema_tatico_pref) VALUES
(1, 'Ofensivo', '4-3-3'),
(2, 'Posicional', '4-2-3-1'),
(3, 'Contra-ataque', '4-4-2'),
(4, 'Agressivo', '4-3-1-2'),
(5, 'Posse de Bola', '3-4-3'),
(6, 'Tiki-taka', '4-3-3'),
(7, 'Direto', '4-2-3-1'),
(8, 'Defensivo', '4-4-2'),
(9, 'Equilibrado', '4-3-3'),
(10, 'Ofensivo', '3-5-2'),
(11, 'Retranca', '3-5-2'),
(12, 'Cadenciado', '4-3-3'),
(13, 'Fisico', '4-3-3'),
(14, 'Veloz', '4-2-3-1'),
(15, 'Intenso', '4-4-2'),
(16, 'Reativo', '4-1-4-1'),
(17, 'Forca', '4-4-2'),
(18, 'Pressao', '4-3-3'),
(19, 'Misto', '4-3-3'),
(20, 'Tatico', '3-4-2-1'),
(21, 'Apoiado', '4-2-3-1'),
(22, 'Compacto', '4-4-2'),
(23, 'Defensivo', '5-4-1'),
(24, 'Fisico', '4-5-1'),
(25, 'Direto', '4-4-2'),
(26, 'Transicao', '3-4-3'),
(27, 'Ofensivo', '4-3-3'),
(28, 'Equilibrado', '4-2-3-1'),
(29, 'Marcacao', '4-4-2'),
(30, 'Reativo', '4-2-3-1');

INSERT INTO preparador_fisico (fk_comissao_tecnica_inscricao, especializacao, metodologia_treino) VALUES
(1, 'Resistencia', 'Treino de Alta Intensidade'),
(2, 'Forca Explosiva', 'Periodizacao Tatica'),
(3, 'Velocidade', 'Treino Funcional'),
(4, 'Recuperacao', 'Crioterapia e Carga Progressiva'),
(5, 'Agilidade', 'Circuitos de Velocidade'),
(6, 'Resistencia Cardiorrespiratoria', 'Metodo HIIT'),
(7, 'Forca Geral', 'Musculacao Tradicional'),
(8, 'Prevencao de Lesoes', 'Core Training'),
(9, 'Potencia', 'Pliometria'),
(10, 'Fisiologia', 'Analise de Carga de Trabalho'),
(11, 'Resistencia', 'Treino Intervalado'),
(12, 'Velocidade de Reacao', 'Treinos Cognitivos'),
(13, 'Massa Muscular', 'Hipertrofia Funcional'),
(14, 'Flexibilidade', 'Pilates Aplicado'),
(15, 'Estabilidade', 'Propriocepcao'),
(16, 'Forca Isotrofica', 'Sobrecarga Excentrica'),
(17, 'Resistencia Anaerobia', 'Zonas de Potencia'),
(18, 'Elasticidade', 'Alongamento Dinamico'),
(19, 'Capacidade Aerobia', 'Fartlek'),
(20, 'Aceleracao', 'Sprints em Rampa'),
(21, 'Equilibrio Dinamico', 'Bosu Training'),
(22, 'Densidade de Carga', 'Treino Integrado'),
(23, 'Resistencia de Forca', 'Isometricos'),
(24, 'Condicionamento', 'Crossfit Adaptado'),
(25, 'Velocidade Linear', 'Paraquedas de Corrida'),
(26, 'Recuperacao Rapida', 'Fisioterapia Esportiva'),
(27, 'Agilidade em Espaco Curto', 'Escada de Agilidade'),
(28, 'Potencia de Salto', 'Caixas Pliometricas'),
(29, 'Condicionamento Geral', 'Running Outdoor'),
(30, 'Oxigenacao', 'Treino em Altitude');

INSERT INTO auxiliar_tecnico (fk_comissao_tecnica_inscricao, especialidade, foco_setorial) VALUES
(1, 'Analise de Video', 'Setor Defensivo'),
(2, 'Bolas Paradas', 'Ataque'),
(3, 'Estrategia de Jogo', 'Meio-Campo'),
(4, 'Scouting', 'Transicoes'),
(5, 'Treinamento de Goleiros', 'Goleiros'),
(6, 'Tatica Coletiva', 'Geral'),
(7, 'Analise Individual', 'Atacantes'),
(8, 'Marcacao Pressao', 'Defesa'),
(9, 'Bolas Paradas Defensivas', 'Zagueiros'),
(10, 'Transicao Ofensiva', 'Pontas'),
(11, 'Tatica de Grupo', 'Meio-Campo'),
(12, 'Analise do Adversario', 'Geral'),
(13, 'Jogadas Ensaiadas', 'Ataque'),
(14, 'Defesa em Linha', 'Zagueiros'),
(15, 'Presenca de Area', 'Centroavantes'),
(16, 'Compactacao', 'Volantes'),
(17, 'Contra-ataque Veloz', 'Laterais'),
(18, 'Marcacao Individual', 'Defesa'),
(19, 'Saida de Bola', 'Zagueiros e Goleiro'),
(20, 'Flutuacao Espacial', 'Meias Criativos'),
(21, 'Bloqueio Baixo', 'Linha de 4'),
(22, 'Pressao no Portador', 'Atacantes'),
(23, 'Cobertura Tatica', 'Laterais'),
(24, 'Ataque Posicional', 'Extremos'),
(25, 'Segunda Bola', 'Volantes'),
(26, 'Cruzamentos', 'Laterais'),
(27, 'Finalizacoes', 'Atacantes'),
(28, 'Duelos Aereos', 'Zagueiros'),
(29, 'Passe Curto', 'Meio-Campo'),
(30, 'Simulacao de Cenarios', 'Geral');

INSERT INTO jogo (id, placar, data, vencedor, perdedor, tipo_jogo) VALUES
(1, '2x1', '2026-06-10 17:00:00', 'Brasil', 'Alemanha', 'Fase de Grupos'),
(2, '3x0', '2026-06-11 14:00:00', 'Franca', 'Argentina', 'Fase de Grupos'),
(3, '1x1', '2026-06-12 20:00:00', 'Empate', 'Empate', 'Fase de Grupos'),
(4, '2x0', '2026-06-13 17:00:00', 'Espanha', 'Belgica', 'Fase de Grupos'),
(5, '4x2', '2026-06-14 11:00:00', 'Portugal', 'Holanda', 'Fase de Grupos'),
(6, '1x0', '2026-06-15 14:00:00', 'Italia', 'Croacia', 'Fase de Grupos'),
(7, '2x1', '2026-06-16 17:00:00', 'Estados Unidos', 'Japao', 'Fase de Grupos'),
(8, '0x0', '2026-06-17 20:00:00', 'Empate', 'Empate', 'Fase de Grupos'),
(9, '3x1', '2026-06-18 11:00:00', 'Senegal', 'Camaroes', 'Fase de Grupos'),
(10, '2x2', '2026-06-19 14:00:00', 'Empate', 'Empate', 'Fase de Grupos'),
(11, '1x0', '2026-06-20 17:00:00', 'Colombia', 'Suecia', 'Fase de Grupos'),
(12, '2x1', '2026-06-21 20:00:00', 'Egito', 'Saudi Arabia', 'Fase de Grupos'),
(13, '3x0', '2026-06-22 11:00:00', 'Australia', 'Canada', 'Fase de Grupos'),
(14, '1x0', '2026-06-23 14:00:00', 'Polonia', 'Chile', 'Fase de Grupos'),
(15, '2x0', '2026-06-24 17:00:00', 'Ucrnia', 'Peru', 'Fase de Grupos'),
(16, '3x2', '2026-06-28 16:00:00', 'Brasil', 'Franca', 'Oitavas de Final'),
(17, '1x0', '2026-06-29 21:00:00', 'Alemanha', 'Argentina', 'Oitavas de Final'),
(18, '2x0', '2026-06-30 16:00:00', 'Espanha', 'Portugal', 'Oitavas de Final'),
(19, '2x1', '2026-07-01 21:00:00', 'Holanda', 'Inglaterra', 'Oitavas de Final'),
(20, '1x0', '2026-07-02 16:00:00', 'Italia', 'Estados Unidos', 'Oitavas de Final'),
(21, '4x1', '2026-07-03 21:00:00', 'Marrocos', 'Senegal', 'Oitavas de Final'),
(22, '2x0', '2026-07-04 16:00:00', 'Suica', 'Colombia', 'Oitavas de Final'),
(23, '1x0', '2026-07-05 21:00:00', 'Croacia', 'Australia', 'Oitavas de Final'),
(24, '2x1', '2026-07-09 17:00:00', 'Brasil', 'Espanha', 'Quartas de Final'),
(25, '3x2', '2026-07-10 21:00:00', 'Alemanha', 'Holanda', 'Quartas de Final'),
(26, '1x0', '2026-07-11 17:00:00', 'Italia', 'Marrocos', 'Quartas de Final'),
(27, '2x0', '2026-07-12 21:00:00', 'Suica', 'Croacia', 'Quartas de Final'),
(28, '2x1', '2026-07-15 20:00:00', 'Brasil', 'Alemanha', 'Semifinal'),
(29, '1x0', '2026-07-16 20:00:00', 'Italia', 'Suica', 'Semifinal'),
(30, '3x2', '2026-07-19 18:00:00', 'Brasil', 'Italia', 'Final');

INSERT INTO contido (fk_jogo_id, fk_selecao_inscricao) VALUES
(1, 1), (1, 2),
(2, 3), (2, 4),
(3, 7), (3, 8),
(4, 6), (4, 5),
(5, 9), (5, 10),
(6, 11), (6, 12),
(7, 13), (7, 14),
(8, 15), (8, 16),
(9, 18), (9, 17),
(10, 19), (10, 20),
(11, 21), (11, 22),
(12, 24), (12, 23),
(13, 25), (13, 26),
(14, 28), (14, 27),
(15, 30), (15, 29);

INSERT INTO jogador (inscricao, numero_da_camisa, posicao, nome, idade, fk_selecao_inscricao, capitao) VALUES
(1, 10, 'Atacante', 'Neymar Jr', 34, 1, NULL),
(2, 9, 'Atacante', 'Ronaldo Gaucho', 28, 1, NULL),
(3, 1, 'Goleiro', 'Alisson Becker', 33, 1, NULL),
(4, 5, 'Volante', 'Casemiro', 34, 1, NULL),
(5, 4, 'Zagueiro', 'Marquinhos', 32, 1, NULL),
(6, 13, 'Lateral', 'Dani Alves', 39, 1, NULL),
(7, 11, 'Meio-Campo', 'Lucas Paqueta', 28, 1, NULL),
(8, 7, 'Atacante', 'Vinicius Jr', 25, 1, NULL),
(9, 10, 'Meio-Campo', 'Thomas Muller', 36, 2, NULL),
(10, 1, 'Goleiro', 'Manuel Neuer', 40, 2, NULL),
(11, 6, 'Volante', 'Joshua Kimmich', 31, 2, NULL),
(12, 10, 'Atacante', 'Kylian Mbappe', 27, 3, NULL),
(13, 7, 'Atacante', 'Antoine Griezmann', 35, 3, NULL),
(14, 10, 'Atacante', 'Lionel Messi', 38, 4, NULL),
(15, 11, 'Atacante', 'Angel Di Maria', 38, 4, NULL),
(16, 7, 'Meio-Campo', 'Kevin De Bruyne', 34, 5, NULL),
(17, 10, 'Meio-Campo', 'Luka Modric', 40, 12, NULL),
(18, 7, 'Atacante', 'Cristiano Ronaldo', 41, 9, NULL),
(19, 8, 'Meio-Campo', 'Bruno Fernandes', 31, 9, NULL),
(20, 21, 'Meio-Campo', 'Frenkie de Jong', 29, 10, NULL),
(21, 4, 'Zagueiro', 'Virgil van Dijk', 34, 10, NULL),
(22, 10, 'Atacante', 'Harry Kane', 32, 7, NULL),
(23, 9, 'Atacante', 'Luis Suarez', 39, 8, NULL),
(24, 10, 'Atacante', 'Sadio Mane', 34, 18, NULL),
(25, 11, 'Atacante', 'Mohamed Salah', 33, 24, NULL),
(26, 10, 'Atacante', 'Christian Pulisic', 27, 13, NULL),
(27, 9, 'Atacante', 'Robert Lewandowski', 37, 28, NULL),
(28, 1, 'Goleiro', 'Thibaut Courtois', 34, 5, NULL),
(29, 2, 'Lateral', 'Achraf Hakimi', 27, 16, NULL),
(30, 10, 'Meio-Campo', 'Granit Xhaka', 33, 20, NULL);

UPDATE jogador SET capitao = 1 WHERE inscricao IN (1,2,3,4,5,6,7,8);
UPDATE jogador SET capitao = 9 WHERE inscricao IN (9,10,11);
UPDATE jogador SET capitao = 12 WHERE inscricao IN (12,13);
UPDATE jogador SET capitao = 14 WHERE inscricao IN (14,15);
UPDATE jogador SET capitao = 16 WHERE inscricao IN (16,28);
UPDATE jogador SET capitao = 18 WHERE inscricao IN (18,19);
UPDATE jogador SET capitao = 21 WHERE inscricao IN (20,21);

INSERT INTO posicao (NomePosicao, inscricao_jogador) VALUES
('Ponta Esquerda', 1),
('Segundo Atacante', 2),
('Goleiro Principal', 3),
('Primeiro Volante', 4),
('Zagueiro Central', 5),
('Lateral Direito', 6),
('Meia Armador', 7),
('Ponta Direita', 8),
('Meia Atacante', 9),
('Goleiro', 10),
('Volante', 11),
('Centroavante', 12),
('Segundo Atacante', 13),
('Meia Atacante', 14),
('Ponta Direita', 15),
('Meia Central', 16),
('Meia Armador', 17),
('Centroavante', 18),
('Meia Atacante', 19),
('Volante Saida', 20),
('Zagueiro Central', 21),
('Centroavante', 22),
('Centroavante', 23),
('Ponta Esquerda', 24),
('Ponta Direita', 25),
('Ponta Esquerda', 26),
('Centroavante', 27),
('Goleiro Principal', 28),
('Lateral Direito', 29),
('Primeiro Volante', 30);

INSERT INTO participa_jogo_estadio_jogador (fk_jogador_inscricao, fk_jogo_id, fk_estadio_id) VALUES
(1, 1, 1), (2, 1, 1), (3, 1, 1), (4, 1, 1), (5, 1, 1),
(6, 1, 1), (7, 1, 1), (8, 1, 1), (9, 1, 1), (10, 1, 1),
(11, 1, 1), (12, 2, 5), (13, 2, 5), (14, 2, 5), (15, 2, 5),
(16, 4, 7), (28, 4, 7), (17, 6, 9), (18, 5, 20), (19, 5, 20),
(20, 5, 20), (21, 5, 20), (22, 3, 11), (23, 3, 11), (24, 9, 18),
(25, 12, 19), (26, 7, 15), (27, 14, 26), (29, 8, 17), (30, 10, 12);