spring.application.name=WordDataCup
spring.datasource.url=jdbc:mariadb://localhost:3306/Atividade_bd9
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver